window.PLATELET_CONTENT = {
  sections: [["home","Home"],["objectives","Learning Objectives"],["background","Background"],["core-content","Core Content"],["mechanisms","Mechanisms"],["clinical-cases","Clinical Case"],["quiz","Knowledge Check"],["summary","Summary"]],
  agonists: {
    adp:{label:"ADP",receptor:"P2Y₁ / P2Y₁₂",result:"72%",normal:"74%",interpretation:"Preserved shape change and aggregation show intact purinergic signaling, GPIIb/IIIa activation, and fibrinogen binding.",patient:"M55 211 C95 211 110 195 135 182 S220 145 290 118 S430 82 720 69",control:"M55 211 C95 211 110 192 135 178 S220 142 290 114 S430 78 720 65"},
    epinephrine:{label:"Epinephrine",receptor:"α₂-adrenergic receptor",result:"61%",normal:"64%",interpretation:"A preserved biphasic response supports intact broader aggregation and secretion machinery; isolated epinephrine hyporesponsiveness can occur in healthy people.",patient:"M55 211 C120 211 135 184 190 171 S270 160 330 143 S410 100 720 91",control:"M55 211 C120 211 135 181 190 168 S270 156 330 139 S410 96 720 86"},
    collagen:{label:"Collagen",receptor:"GPVI / integrin α₂β₁",result:"70%",normal:"73%",interpretation:"The normal lag followed by strong irreversible aggregation argues against a major GPVI-associated defect or severe global secretion defect.",patient:"M55 211 C150 211 170 210 205 193 S250 135 340 108 S510 76 720 72",control:"M55 211 C145 211 165 209 200 188 S250 130 340 103 S510 72 720 68"},
    arachidonic:{label:"Arachidonic acid",receptor:"COX-1 → thromboxane A₂",result:"75%",normal:"78%",interpretation:"A strong irreversible response shows an intact cyclooxygenase–thromboxane pathway and no aspirin-like pattern.",patient:"M55 211 C105 211 125 186 165 157 S240 100 340 82 S510 66 720 65",control:"M55 211 C105 211 125 181 165 151 S240 94 340 76 S510 61 720 60"},
    trap:{label:"TRAP",receptor:"PAR thrombin receptor",result:"79%",normal:"81%",interpretation:"Strong activation through the thrombin-receptor pathway confirms preserved GPIIb/IIIa-dependent aggregation.",patient:"M55 211 C95 211 105 180 150 142 S230 83 340 68 S520 57 720 56",control:"M55 211 C95 211 105 176 150 137 S230 79 340 64 S520 53 720 52"},
    ristocetin:{label:"High-dose ristocetin",receptor:"VWF ↔ GPIb-IX-V",result:"2%",normal:"78%",interpretation:"The nearly flat patient tracing localizes the functional failure to the VWF–GPIb interaction. Crossover studies are required to distinguish plasma VWF from the platelet receptor.",patient:"M55 211 C160 211 250 209 340 208 S550 207 720 206",control:"M55 211 C95 211 115 180 160 143 S250 85 350 69 S520 59 720 58"}
  }
};

window.PLATELET_QUIZ = [
  {q:"Which finding most strongly supports an inherited macrothrombocytopenia?",choices:["Prolonged PT","Numerous giant platelets with an affected sibling","Schistocytes with renal injury","Isolated low fibrinogen"],answer:1,explain:"Giant platelets, chronic thrombocytopenia, lifelong mucocutaneous bleeding, and a compatible family history strongly support an inherited macrothrombocytopenia."},
  {q:"Why must LTA results be interpreted cautiously at a platelet count near 55 × 10⁹/L?",choices:["Citrate becomes inactive","Low platelet concentration and abnormal size change optical responses","Ristocetin destroys platelets","PPP cannot be prepared"],answer:1,explain:"Both platelet concentration and optical properties influence LTA. Macrothrombocytopenic patient PRP should be compared with count-matched control PRP."},
  {q:"As platelets aggregate in PRP, what happens to light transmission?",choices:["It increases as the suspension clears","It decreases as the suspension clears","It remains fixed at 0%","It becomes independent of PPP"],answer:0,explain:"Aggregates clear the suspension, so more light reaches the detector. PPP serves as the clear optical reference."},
  {q:"Which agonist pattern is classic for Bernard–Soulier syndrome?",choices:["All agonists absent except ristocetin","Conventional agonists preserved; ristocetin absent","Only arachidonic acid absent","Low-dose ristocetin enhanced"],answer:1,explain:"GPIIb/IIIa-dependent aggregation remains broadly intact, while VWF–GPIb-dependent ristocetin agglutination is absent or markedly reduced."},
  {q:"The initial optical response to ristocetin is best described as:",choices:["Secretion","Coagulation","Agglutination","Fibrinolysis"],answer:2,explain:"Ristocetin induces VWF binding to platelet GPIb-IX-V, producing agglutination rather than conventional fibrinogen-mediated aggregation."},
  {q:"Absent high-dose ristocetin responsiveness with normal conventional agonists initially localizes the problem to:",choices:["The VWF–GPIb interaction","The cyclooxygenase pathway","P2Y₁₂ only","GPIIb/IIIa only"],answer:0,explain:"The pattern identifies a failure somewhere between plasma VWF and platelet GPIb-IX-V; it does not by itself specify which side is abnormal."},
  {q:"Patient platelets remain unresponsive in normal plasma. What does this show?",choices:["Normal VWF corrects the defect","The defect travels with patient platelets","Patient plasma lacks VWF","The finding proves Glanzmann thrombasthenia"],answer:1,explain:"Failure of normal plasma to rescue patient platelets localizes the abnormality to the platelet side of the interaction."},
  {q:"Which flow-cytometry combination supports Bernard–Soulier syndrome?",choices:["CD42b reduced; CD41/CD61 preserved","CD42b preserved; CD41/CD61 absent","All markers preserved","CD9 absent alone"],answer:0,explain:"CD42b and CD42a assess the GPIb-IX-V complex; CD41 and CD61 assess GPIIb/IIIa, which is preserved in classic Bernard–Soulier syndrome."},
  {q:"Which finding argues against type 2B VWD and platelet-type VWD?",choices:["Thrombocytopenia","Large platelets","No enhanced low-dose ristocetin response","Mucocutaneous bleeding"],answer:2,explain:"Type 2B VWD and platelet-type VWD characteristically show gain-of-function interaction and enhanced response at abnormally low ristocetin concentrations."},
  {q:"Which genes are appropriate targets for molecular confirmation?",choices:["F8, F9, F11","VWF only","GP1BA, GP1BB, and GP9","ITGA2B and ITGB3 only"],answer:2,explain:"GP1BA, GP1BB, and GP9 encode components of the GPIb-IX-V receptor complex and are established Bernard–Soulier syndrome genes."}
];

(function(){
  const key="coag-case6-quiz"; let state={index:0,score:0,answers:[],finished:false};
  const read=()=>{try{return JSON.parse(localStorage.getItem(key))||state}catch{return state}}; const save=()=>localStorage.setItem(key,JSON.stringify(state));
  function render(){const root=document.querySelector("#quiz-root");if(!root)return;if(state.finished){const pct=Math.round(state.score/PLATELET_QUIZ.length*100);root.innerHTML=`<div class="quiz-result"><div class="quiz-score">${state.score}/${PLATELET_QUIZ.length}</div><h2>${pct>=80?"Strong pattern recognition":pct>=60?"Nearly there":"Review the localization pathway"}</h2><p>${pct>=80?"You can connect aggregation patterns to the affected receptor.":"Use the explanations to revisit the concepts that caused difficulty."}</p><button class="button button-primary" id="quiz-restart">Retake knowledge check</button></div>`;document.querySelector("#quiz-bar").style.width="100%";window.markSectionComplete?.("quiz");document.querySelector("#quiz-restart").addEventListener("click",reset);return}const item=PLATELET_QUIZ[state.index],answered=state.answers[state.index];root.innerHTML=`<p class="quiz-kicker">Question ${state.index+1} of ${PLATELET_QUIZ.length}</p><h2>${item.q}</h2><div class="choice-group quiz-choices">${item.choices.map((c,i)=>`<button class="choice ${answered!==undefined?(i===item.answer?"correct":i===answered?"incorrect":""):""}" data-index="${i}" ${answered!==undefined?"disabled":""}><span>${String.fromCharCode(65+i)}</span>${c}</button>`).join("")}</div>${answered!==undefined?`<div class="quiz-explanation ${answered===item.answer?"is-correct":"is-incorrect"}"><strong>${answered===item.answer?"Correct":"Not quite"}</strong><p>${item.explain}</p></div><button class="button button-primary" id="quiz-next">${state.index===PLATELET_QUIZ.length-1?"See results":"Next question →"}</button>`:""}`;document.querySelector("#quiz-bar").style.width=`${state.index/PLATELET_QUIZ.length*100}%`;if(answered===undefined)root.querySelectorAll(".choice").forEach(b=>b.addEventListener("click",()=>answer(Number(b.dataset.index))));else document.querySelector("#quiz-next").addEventListener("click",next)}
  function answer(i){state.answers[state.index]=i;if(i===PLATELET_QUIZ[state.index].answer)state.score++;save();render()} function next(){if(state.index===PLATELET_QUIZ.length-1)state.finished=true;else state.index++;save();render()} function reset(){state={index:0,score:0,answers:[],finished:false};save();render()}
  window.resetPlateletQuiz=reset;document.addEventListener("DOMContentLoaded",()=>{state=read();render()});
})();

const progressKey="coag-case6-progress",caseKey="coag-case6-clinical",sections=PLATELET_CONTENT.sections;
const readJSON=(key,fallback={})=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};

function renderSidebar(){const sidebar=document.querySelector("#sidebar");sidebar.innerHTML=`<div class="brand"><div class="brand-mark">PLT</div><div><strong>Classic Platelet Aggregation</strong><span>Resident learning module</span></div></div><nav class="nav-list" aria-label="Module sections">${sections.map(([id,name],i)=>`<a class="nav-link ${i===0?"active":""}" data-nav="${id}" href="#${id}"><span class="nav-number">${String(i+1).padStart(2,"0")}</span><span>${name}</span><span class="nav-check" aria-hidden="true"></span></a>`).join("")}</nav><div class="sidebar-progress"><div class="progress-label"><span>Module progress</span><span id="progress-text">0%</span></div><div class="progress-track"><div class="progress-fill" id="progress-fill"></div></div><button class="reset-button" id="reset-progress">Reset all progress</button></div>`;updateProgress()}
function updateProgress(){const p=readJSON(progressKey),done=sections.filter(([id])=>p[id]).length,pct=Math.round(done/sections.length*100);document.querySelectorAll(".nav-link").forEach(l=>l.classList.toggle("complete",!!p[l.dataset.nav]));document.querySelector("#progress-fill").style.width=`${pct}%`;document.querySelector("#progress-text").textContent=`${pct}%`;const start=document.querySelector("#start-button");if(start&&done>1){start.innerHTML='Resume module <span aria-hidden="true">→</span>';start.href=`#${p.last||"objectives"}`}}
window.markSectionComplete=id=>{const p=readJSON(progressKey);p[id]=true;p.last=id;localStorage.setItem(progressKey,JSON.stringify(p));updateProgress()};
function setupNavigation(){const menu=document.querySelector("#menu-button"),sidebar=document.querySelector("#sidebar");menu.addEventListener("click",()=>{const open=sidebar.classList.toggle("open");menu.setAttribute("aria-expanded",String(open))});document.querySelectorAll(".nav-link").forEach(l=>l.addEventListener("click",()=>{sidebar.classList.remove("open");menu.setAttribute("aria-expanded","false")}));document.querySelector("#reset-progress").addEventListener("click",()=>{if(confirm("Reset module progress, clinical case, and quiz results?")){[progressKey,caseKey,"coag-case6-quiz"].forEach(k=>localStorage.removeItem(k));location.reload()}});const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const id=e.target.id;document.querySelectorAll(".nav-link").forEach(l=>l.classList.toggle("active",l.dataset.nav===id));history.replaceState(null,"",`#${id}`);window.markSectionComplete(id)}),{rootMargin:"-35% 0px -55% 0px",threshold:0});document.querySelectorAll(".module-section").forEach(s=>observer.observe(s))}

function traceSVG(item){return `<div class="trace-panel"><svg viewBox="0 0 760 250" role="img" aria-label="${item.label} patient and count-matched control tracings"><line class="trace-axis" x1="55" y1="15" x2="55" y2="215"/><line class="trace-axis" x1="55" y1="215" x2="735" y2="215"/><line class="trace-grid" x1="55" y1="65" x2="735" y2="65"/><line class="trace-grid" x1="55" y1="115" x2="735" y2="115"/><line class="trace-grid" x1="55" y1="165" x2="735" y2="165"/><text x="8" y="25" font-size="12" fill="#607784">100%</text><text x="20" y="218" font-size="12" fill="#607784">0%</text><path class="trace-line control" d="${item.control}"/><path class="trace-line patient" d="${item.patient}"/></svg><div class="trace-legend"><span><i class="patient-key"></i>Patient ${item.result}</span><span><i></i>Count-matched control ${item.normal}</span></div></div>`}
function renderAgonist(name){const d=PLATELET_CONTENT.agonists[name],abnormal=name==="ristocetin";document.querySelector("#agonist-stage").innerHTML=`<div><p class="step-kicker">Receptor / pathway</p><h2>${d.label}</h2><p><strong>${d.receptor}</strong></p><div class="agonist-result ${abnormal?"abnormal":""}">${d.result} <small>patient maximum response</small></div><p>${d.interpretation}</p></div>${traceSVG(d)}`}
function setupAgonists(){const tabs=document.querySelector(".agonist-tabs");tabs.innerHTML=Object.entries(PLATELET_CONTENT.agonists).map(([id,d],i)=>`<button class="agonist-tab ${i===0?"active":""}" role="tab" aria-selected="${i===0}" data-agonist="${id}">${d.label}</button>`).join("");renderAgonist("adp");tabs.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{tabs.querySelectorAll("button").forEach(x=>{x.classList.toggle("active",x===b);x.setAttribute("aria-selected",String(x===b))});renderAgonist(b.dataset.agonist)}))}

let caseState={step:0,completed:[]};
const explanations=["The phenotype is mucocutaneous, indicating impaired primary hemostasis rather than the deep-tissue pattern typical of severe factor deficiencies.","Giant platelets with chronic thrombocytopenia and a compatible recessive family pattern strongly suggest Bernard–Soulier syndrome, while the smear also excludes clumping and schistocytes.","The low count can weaken optical responses. Native patient PRP should be interpreted against healthy control PRP diluted to approximately the same platelet count.","Preserved responses show that platelets can activate GPIIb/IIIa, bind fibrinogen, and signal through multiple activation and secretion pathways.","Absent ristocetin response identifies a severe problem in the VWF–GPIb interaction, but either plasma VWF or the platelet receptor could be responsible.","Normal VWF does not rescue patient platelets, while patient plasma supports normal platelets. The abnormality therefore travels with the platelets.","CD42b and CD42a represent GPIbα and GPIX. Their marked reduction with preserved CD41/CD61 confirms selective loss of GPIb-IX-V rather than GPIIb/IIIa."];
function showCaseStep(){document.querySelectorAll(".case-step").forEach((e,i)=>{e.hidden=i!==caseState.step;e.classList.toggle("active",i===caseState.step)});const n=Math.min(caseState.completed.length,7);document.querySelector("#case-progress-text").textContent=`${n} / 7 decisions`;document.querySelector("#case-progress-fill").style.width=`${n/7*100}%`;document.querySelector("#case-complete").hidden=caseState.step<7}
function advanceCase(step,feedback){if(!caseState.completed.includes(step))caseState.completed.push(step);localStorage.setItem(caseKey,JSON.stringify(caseState));feedback.className="case-feedback success";feedback.innerHTML=`<strong>Well reasoned.</strong><p>${explanations[step]}</p><button class="button button-primary case-next">${step===6?"Reveal diagnosis →":"Continue →"}</button>`;feedback.querySelector(".case-next").addEventListener("click",()=>{caseState.step=step+1;localStorage.setItem(caseKey,JSON.stringify(caseState));showCaseStep();if(caseState.step===7){window.markSectionComplete("clinical-cases");document.querySelector("#case-complete").scrollIntoView({behavior:"smooth",block:"center"})}else document.querySelector(`[data-case-step="${caseState.step}"]`).scrollIntoView({behavior:"smooth",block:"center"})})}
function setupCase(){caseState=readJSON(caseKey,{step:0,completed:[]});if(caseState.step>7)caseState.step=7;showCaseStep();document.querySelectorAll(".case-step .choice").forEach(button=>button.addEventListener("click",()=>{const parent=button.closest(".case-step"),step=Number(parent.dataset.caseStep),feedback=parent.querySelector(".case-feedback");button.parentElement.querySelectorAll(".choice").forEach(b=>b.classList.remove("selected","correct","incorrect"));button.classList.add("selected",button.dataset.correct==="true"?"correct":"incorrect");if(button.dataset.correct==="true")advanceCase(step,feedback);else{feedback.className="case-feedback error";feedback.innerHTML="<strong>Reconsider the pattern.</strong><p>Choose the most precise conclusion supported by the information available at this step.</p>"}}));document.querySelector("#restart-case").addEventListener("click",()=>{caseState={step:0,completed:[]};localStorage.setItem(caseKey,JSON.stringify(caseState));showCaseStep();location.hash="clinical-cases"});document.querySelector("#retake-quiz").addEventListener("click",()=>{window.resetPlateletQuiz?.();location.hash="quiz"})}

document.addEventListener("DOMContentLoaded",()=>{renderSidebar();setupNavigation();setupAgonists();setupCase()});
