const STORAGE_KEY="case11-sendout-progress-v1";
const sectionIds=["home","objectives","background","core","mechanisms","cases","quiz","summary"];
let state={visited:[],cases:[],quiz:{},summary:false};

function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(saved)state={...state,...saved};state.visited=state.visited.filter(id=>sectionIds.includes(id))}catch(error){console.warn("Progress could not be loaded",error)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateProgress()}
function flash(message){const toast=document.querySelector("#toast");toast.textContent=message;toast.classList.add("show");clearTimeout(flash.timer);flash.timer=setTimeout(()=>toast.classList.remove("show"),2200)}
function updateProgress(){
  const sectionPoints=state.visited.length/sectionIds.length*55;
  const casePoints=state.cases.length/4*20;
  const quizPoints=Object.keys(state.quiz).length/10*20;
  const summaryPoints=state.summary?5:0;
  const percent=Math.round(sectionPoints+casePoints+quizPoints+summaryPoints);
  document.querySelector("#progress-label").textContent=`${percent}%`;
  document.querySelector("#progress-bar").style.width=`${percent}%`;
  document.querySelector("#progress-detail").textContent=`${state.visited.length} of 8 sections visited`;
  document.querySelectorAll(".nav-link").forEach(link=>link.classList.toggle("visited",state.visited.includes(link.hash.slice(1))));
  document.querySelector("#case-count").textContent=`${state.cases.length} / 4 cases completed`;
  document.querySelector("#case-progress").style.width=`${state.cases.length/4*100}%`;
  document.querySelector("#begin-module").textContent=percent>5?"Resume module":"Begin module";
}

const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){
  const id=entry.target.id;document.querySelectorAll(".nav-link").forEach(link=>link.classList.toggle("active",link.hash===`#${id}`));
  if(!state.visited.includes(id)){state.visited.push(id);save()}
}}),{rootMargin:"-35% 0px -55%",threshold:0});
document.querySelectorAll("[data-section]").forEach(section=>observer.observe(section));

const menu=document.querySelector(".sidebar"),menuButton=document.querySelector(".menu-toggle");
menuButton.addEventListener("click",()=>{const open=menu.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open));menuButton.setAttribute("aria-label",open?"Close module navigation":"Open module navigation")});
document.querySelectorAll(".nav-link").forEach(link=>link.addEventListener("click",()=>{menu.classList.remove("open");menuButton.setAttribute("aria-expanded","false")}));

document.querySelectorAll("[data-lens]").forEach(button=>button.addEventListener("click",()=>{
  document.querySelectorAll("[data-lens]").forEach(item=>{item.classList.toggle("active",item===button);item.setAttribute("aria-selected",String(item===button))});
  document.querySelectorAll("[data-lens-panel]").forEach(panel=>{const active=panel.dataset.lensPanel===button.dataset.lens;panel.hidden=!active;panel.classList.toggle("active",active)});
}));

const sortItems=[
  {q:"“Can you send me the vendor kit?”",answer:"staff",why:"Kit logistics are an operational send-out or customer-service question."},
  {q:"“Is mass spectrometry preferable to this immunoassay for my patient?”",answer:"resident",why:"Method selection in a clinical context is an appropriate resident or laboratory-physician consultation."},
  {q:"“Was the miscellaneous test order entered correctly?”",answer:"staff",why:"Routine order-entry verification belongs first with send-out staff or customer service."},
  {q:"“Could cross-reactivity explain this discordant result?”",answer:"resident",why:"Analytical limitations and clinical interpretation require scientific consultation."}
];
let sortIndex=0;
function renderSort(){document.querySelector("#sort-prompt").textContent=sortItems[sortIndex].q;document.querySelector("#sort-feedback").className="sort-feedback";document.querySelector("#sort-feedback").textContent="Choose the most appropriate first contact.";document.querySelectorAll("[data-route]").forEach(b=>b.classList.remove("selected"))}
document.querySelectorAll("[data-route]").forEach(button=>button.addEventListener("click",()=>{const correct=button.dataset.route===sortItems[sortIndex].answer;document.querySelectorAll("[data-route]").forEach(b=>b.classList.toggle("selected",b===button));const feedback=document.querySelector("#sort-feedback");feedback.className=`sort-feedback ${correct?"good":"bad"}`;feedback.textContent=`${correct?"Correct.":"Reconsider the first contact."} ${sortItems[sortIndex].why}`}));
document.querySelector("#next-sort").addEventListener("click",()=>{sortIndex=(sortIndex+1)%sortItems.length;renderSort()});

const stages={
  order:{phase:"Stage 01 · Ordering",title:"Convert intent into a complete, traceable request.",copy:"The clinical team places the correct EHR order and completes required vendor requisitions with sufficient clinical information.",verify:"Patient, test, performing laboratory, indication, authorization, and required forms",failure:"Duplicate or low-value testing, ambiguous miscellaneous order, missing requisition",resident:"Clarify medical necessity or test choice; do not routinely complete the clinical team's requisition"},
  collect:{phase:"Stage 02 · Collection",title:"Collect for the performing method, not a generic test name.",copy:"Container, source, timing, volume, preservative, and collection technique must match current reference-laboratory requirements.",verify:"Preferred and minimum volume, tube or kit, collection time, consent, and patient preparation",failure:"Wrong tube, insufficient volume, contamination, or missing paired specimen",resident:"Review feasibility before an unusual or irreplaceable collection"},
  receive:{phase:"Stage 03 · Receipt",title:"Identify mismatches while a correction is still possible.",copy:"The laboratory accessions the specimen, verifies patient and order information, and assesses integrity against acceptance criteria.",verify:"Two identifiers, order match, source, quantity, condition, time, and temperature",failure:"Leakage, mislabeling, clotting, hemolysis, thawing, or unlinked paperwork",resident:"Help resolve clinical ambiguity when staff cannot reconcile the request"},
  prepare:{phase:"Stage 04 · Preparation",title:"Preserve the analyte through every manipulation.",copy:"Send-out staff review requirements, aliquot or process when indicated, and assemble compliant secondary and outer packaging.",verify:"Centrifugation, separation, aliquot material, light protection, absorbent material, and packaging",failure:"Processing delay, transfer error, improper aliquot, or noncompliant packaging",resident:"Support unusual specimen decisions; trained staff own routine preparation and packaging"},
  transport:{phase:"Stage 05 · Transport",title:"Control time, temperature, route, and arrival window.",copy:"Staff select the correct condition, refrigerant, courier service, pickup cutoff, and receiving schedule.",verify:"Stability window, ambient/refrigerated/frozen condition, tracking, weekend and holiday acceptance",failure:"Missed courier, temperature excursion, dry-ice problem, delay, or arrival when the lab is closed",resident:"Help weigh specimen stability against clinical urgency when routine options fail"},
  result:{phase:"Stage 06 · Result",title:"A result is complete only when it reaches the right record and person.",copy:"The reference laboratory performs its checks and reports through an interface, portal, fax, or other approved channel.",verify:"Patient match, units, reference interval, method, corrected status, interface posting, and critical-result routing",failure:"Delayed report, interface failure, transcription error, or incorrect interpretation",resident:"Interpret limitations, support exceptions, and help close urgent communication loops when involved"}
};
document.querySelectorAll("[data-stage]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-stage]").forEach(b=>b.classList.toggle("active",b===button));const item=stages[button.dataset.stage];["phase","title","copy","verify","failure","resident"].forEach(key=>document.querySelector(`#stage-${key}`).textContent=item[key])}));
const temperatures={ambient:"Use only when the current test directory permits ambient transport for the full expected transit time. Protect from prohibited heat, cold, and light exposure.",refrigerated:"Maintain the specified refrigerated range with validated packaging; prevent direct contact that could freeze the specimen and document excursions.",frozen:"Freeze and ship at the required temperature. Confirm whether one freeze–thaw cycle is acceptable and whether dry ice is required or permitted."};
document.querySelectorAll("[data-temp]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-temp]").forEach(b=>b.classList.toggle("selected",b===button));document.querySelector("#temperature-copy").textContent=temperatures[button.dataset.temp]}));

document.querySelectorAll("[data-case-target]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-case-target]").forEach(b=>b.classList.toggle("active",b===button));document.querySelectorAll("[data-case-panel]").forEach(panel=>{const active=panel.id===`case-${button.dataset.caseTarget}`;panel.hidden=!active;panel.classList.toggle("active",active)})}));
document.querySelectorAll("[data-case-panel] fieldset button").forEach(button=>button.addEventListener("click",()=>{const panel=button.closest("[data-case-panel]");panel.querySelectorAll("fieldset button").forEach(b=>b.classList.remove("best","partial","poor"));button.classList.add(button.dataset.quality);const feedback=panel.querySelector(".case-feedback");feedback.className=`case-feedback show ${button.dataset.quality}`;feedback.innerHTML=`<strong>${button.dataset.quality==="best"?"Best response.":button.dataset.quality==="partial"?"Partly defensible.":"Unsafe or incomplete."}</strong> ${button.dataset.feedback}`;if(!state.cases.includes(panel.dataset.caseId)){state.cases.push(panel.dataset.caseId);save()}}));
document.querySelectorAll(".reveal-button").forEach(button=>button.addEventListener("click",()=>{const panel=button.nextElementSibling;panel.hidden=!panel.hidden;button.textContent=panel.hidden?button.textContent.replace("Hide","Reveal"):button.textContent.replace("Reveal","Hide")}));

const quizQuestions=[
  {q:"Which combination best supports sending a test to a reference laboratory?",a:["Low local volume, specialized expertise, and acceptable turnaround time","A vendor representative prefers external testing","The assay is newer and more expensive","The ordering clinician names a brand"],correct:0,e:"Send-out decisions should balance clinical value, analytical performance, operational feasibility, turnaround time, and cost."},
  {q:"A clinician asks whether an immunoassay and a mass spectrometry assay are interchangeable. Who should address the question?",a:["Courier","Billing office","Resident or laboratory physician with relevant expertise","No one; identical analytes guarantee interchangeability"],correct:2,e:"This is a method and clinical-interpretation question. Assays for the same analyte may differ materially."},
  {q:"When should specimen requirements be checked?",a:["Before collection","After the reference laboratory rejects it","Only when the test is expensive","After the courier departs"],correct:0,e:"Container, volume, processing, stability, and transport must be confirmed before collection whenever possible."},
  {q:"Who ordinarily completes a vendor requisition containing clinical information?",a:["The pathology resident","The clinical team","The courier","The reference laboratory after receipt"],correct:1,e:"The source material assigns required clinical requisitions to the clinical team, with laboratory staff supporting the operational pathway."},
  {q:"Which is an operational failure point?",a:["A clinically meaningful phenotype","An unapproved vendor and missing requisition","Appropriate aliquoting","A verified electronic interface"],correct:1,e:"Vendor approval, forms, billing, and routing are operational controls."},
  {q:"A limited CSF specimen cannot support all requested tests. Who owns clinical prioritization?",a:["The clinical team, informed by laboratory constraints","The courier","The vendor sales representative","The interface analyst"],correct:0,e:"Laboratory staff define feasibility; the clinical team prioritizes the clinical questions. The decision should be closed-loop and documented."},
  {q:"Which item is most important when comparing an approved assay with a requested proprietary assay?",a:["Brand familiarity alone","Whether the website looks current","Intended use, methodology, performance, specimen, and report","The length of the test name"],correct:2,e:"Equivalence is a clinical and analytical comparison, not a branding decision."},
  {q:"A critical portal result has not crossed into the EHR. What is the appropriate response?",a:["Wait indefinitely for the interface","Follow the critical-result and interface-downtime pathway","Delete the portal notification","Assume the care team saw it"],correct:1,e:"Critical results require timely closed-loop communication and documentation under local policy."},
  {q:"Which statement about specimen packaging is correct?",a:["Any staff member may package regulated material after reading this module","Temperature requirements are optional if transit is short","Trained personnel must follow current institutional and transport requirements","All specimens use the same packaging"],correct:2,e:"Classification, packaging, labeling, refrigerant, and transport rules require current training and applicable procedures."},
  {q:"Which statement best summarizes the resident's role?",a:["Perform every routine send-out bench task","Focus only on cost","Add clinical and scientific judgment while respecting operational ownership","Approve every request from a specialist"],correct:2,e:"Residents contribute test selection, method knowledge, interpretation, escalation, stewardship, and quality improvement."}
];
function renderQuiz(){const list=document.querySelector("#quiz-list");list.innerHTML=quizQuestions.map((item,index)=>`<article class="quiz-question" data-quiz="${index}"><h3><span>${String(index+1).padStart(2,"0")}</span>${item.q}</h3><div class="answer-options">${item.a.map((answer,i)=>`<button type="button" data-answer="${i}">${answer}</button>`).join("")}</div><div class="quiz-feedback" aria-live="polite"></div></article>`).join("");Object.keys(state.quiz).forEach(index=>restoreQuestion(Number(index)));list.querySelectorAll("[data-answer]").forEach(button=>button.addEventListener("click",()=>answerQuestion(button)));showQuizResult()}
function answerQuestion(button){const block=button.closest("[data-quiz]"),index=Number(block.dataset.quiz);if(Object.hasOwn(state.quiz,index))return;const chosen=Number(button.dataset.answer);state.quiz[index]={chosen,correct:chosen===quizQuestions[index].correct};save();restoreQuestion(index);showQuizResult()}
function restoreQuestion(index){const block=document.querySelector(`[data-quiz="${index}"]`),record=state.quiz[index];if(!block||!record)return;block.querySelectorAll("[data-answer]").forEach(button=>{const answer=Number(button.dataset.answer);button.disabled=true;if(answer===quizQuestions[index].correct)button.classList.add("correct");if(answer===record.chosen&&!record.correct)button.classList.add("incorrect")});const feedback=block.querySelector(".quiz-feedback");feedback.className=`quiz-feedback show ${record.correct?"correct":"incorrect"}`;feedback.innerHTML=`<strong>${record.correct?"Correct.":"Not quite."}</strong> ${quizQuestions[index].e}`}
function showQuizResult(){const result=document.querySelector("#quiz-result"),answered=Object.keys(state.quiz).length;if(answered<quizQuestions.length){result.hidden=true;return}const score=Object.values(state.quiz).filter(item=>item.correct).length;result.hidden=false;result.innerHTML=`<h3>${score>=8?"Completion threshold reached.":"Review the missed explanations and retry."}</h3><p>You scored ${score} of ${quizQuestions.length} (${score*10}%).</p>`}
document.querySelector("#retry-quiz").addEventListener("click",()=>{state.quiz={};save();renderQuiz();flash("Knowledge check reset.")});
document.querySelector("#mark-summary").addEventListener("click",()=>{state.summary=true;if(!state.visited.includes("summary"))state.visited.push("summary");save();flash("Summary marked as reviewed.")});
document.querySelector("#reset-progress").addEventListener("click",()=>{if(!window.confirm("Reset all section, case, and quiz progress for this module?"))return;state={visited:[],cases:[],quiz:{},summary:false};save();renderQuiz();document.querySelectorAll(".case-feedback").forEach(item=>{item.className="case-feedback";item.textContent="Choose a response to see the stewardship reasoning."});document.querySelectorAll("[data-case-panel] fieldset button").forEach(item=>item.classList.remove("best","partial","poor"));location.hash="#home";flash("Module progress reset.")});

load();renderQuiz();updateProgress();
